export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const CLEAR_VENUES = 'CLEAR_VENUES';

export const GET_ERRORS = 'GET_ERRORS';
export const REMOVE_ERRORS = 'REMOVE_ERRORS';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const SET_PROFILE_LOADING = 'SET_PROFILE_LOADING';
export const PROFILE_LOADED = 'PROFILE_LOADED';
export const PROFILE_ERROR = 'PROFILE_ERROR';

export const VENUES_LOADED = 'VENUES_LOADED';
export const VENUES_ERROR = 'VENUES_ERROR';
export const SET_SELECTED_VENUE = 'SET_SELECTED_VENUE';
export const SELECTED_VENUE_SUCCESS = 'SELECTED_VENUE_SUCCESS';
export const SELECTED_VENUE_FAILED = 'VENUE_FAILED';
