export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const CLEAR_VENUES = 'CLEAR_VENUES';
export const CLEAR_RECIPES = 'CLEAR_RECIPES';
export const CLEAR_INGREDIENTS = 'CLEAR_INGREDIENTS';
export const CLEAR_SUPPLIERS = 'CLEAR_SUPPLIERS';

export const GET_ERRORS = 'GET_ERRORS';
export const REMOVE_ERRORS = 'REMOVE_ERRORS';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';
export const LOAD_RESET_TOKEN = 'LOAD_RESET_TOKEN';
export const REMOVE_RESET_TOKEN = 'REMOVE_RESET_TOKEN';
export const LOAD_RESET_FORM = 'LOAD_RESET_FORM';
export const REMOVE_RESET_FORM_TOKEN = 'REMOVE_RESET_FORM_TOKEN';
export const LOGOUT = 'LOGOUT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const PASSWORD_FAILED = 'PASSWORD_FAILED';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const SET_PROFILE_LOADING = 'SET_PROFILE_LOADING';
export const REMOVE_PROFILE_LOADING = 'REMOVE_PROFILE_LOADING';
export const PROFILE_LOADED = 'PROFILE_LOADED';
export const PROFILE_ERROR = 'PROFILE_ERROR';

export const SET_VENUE_LOADING = 'SET_VENUE_LOADING';
export const STOP_VENUE_LOADING = 'STOP_VENUE_LOADING';
export const VENUES_LOADED = 'VENUES_LOADED';
export const VENUES_ERROR = 'VENUES_ERROR';
export const SET_SELECTED_VENUE = 'SET_SELECTED_VENUE';
export const SELECTED_VENUE_SUCCESS = 'SELECTED_VENUE_SUCCESS';
export const SELECTED_VENUE_FAILED = 'SELECTED_VENUE_FAILED';

export const SET_RECIPES_LOADING = 'SET_RECIPES_LOADING';
export const STOP_RECIPES_LOADING = 'STOP_RECIPES_LOADING';
export const RECIPES_LOADED = 'RECIPES_LOADED';
export const RECIPES_ERROR = 'RECIPES_ERROR';
export const ADD_NEW_RECIPE = 'ADD_NEW_RECIPE';
export const SET_SELECTED_RECIPE = 'SET_SELECTED_RECIPE';
export const UPDATE_SELECTED_RECIPE_STATE =
  'UPDATE_SELECTED_RECIPE_STATE';

export const SET_INGREDIENTS_LOADING = 'SET_INGREDIENTS_LOADING';
export const STOP_INGREDIENTS_LOADING = 'STOP_INGREDIENTS_LOADING';
export const INGREDIENTS_LOADED = 'INGREDIENTS_LOADED';
export const INGREDIENTS_ERROR = 'INGREDIENTS_ERROR';
export const REMOVE_SELECTED_INGREDIENT =
  'REMOVE_SELECTED_INGREDIENT';
export const SET_SELECTED_INGREDIENT = 'SET_SELECTED_INGREDIENT';

export const SET_SUPPLIERS_LOADING = 'SET_SUPPLIERS_LOADING';
export const STOP_SUPPLIERS_LOADING = 'STOP_INGREDIENTS_LOADING';
export const SUPPLIERS_LOADED = 'SUPPLIERS_LOADED';
export const SUPPLIERS_ERROR = 'SUPPLIERS_ERROR';
export const REMOVE_SELECTED_SUPPLIER = 'REMOVE_SELECTED_SUPPLIER';
export const SET_SELECTED_SUPPLIER = 'SET_SELECTED_SUPPLIER';
export const SET_UPDATED_SELECTED_SUPPLIER =
  'SET_UPDATED_SELECTED_SUPPLIER';
export const SET_PREFERRED_SUPPLIER = 'SET_PREFERRED_SUPPLIER';
export const REMOVE_PREFERRED_SUPPLIER = 'REMOVE_PREFERRED_SUPPLIER';
